name: flutter_plot
description: A pretty plotting package for Flutter apps.
version: 0.1.0
homepage: https://github.com/RCHowell/flutter_plot
documentation:
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
